---
- name: Install common software
  apt: name={{item}} state=present update-cache=yes cache_valid_time=864000
  with_items:
    - htop
    - strace
    - make
    - gcc
    - lsof
    - vim
    - curl
    - git
    - mc
    - sysstat
    - iotop
    - dstat
    - iptraf
    - screen
    - tmux
    - zsh

- name: Set hostname
  hostname: name={{common_hostname}}

- name: Update hosts - add hostname to /etc/hosts
  lineinfile: 'line="127.0.0.1 {{common_hostname}}" dest=/etc/hosts state=present'

- name: Ensure that locale is present
  locale_gen: name={{common_locale}} state=present

- name: Set locale
  template: src=default.j2 dest=/etc/default/locale

- name: Set timezone variables
  copy: content={{common_timezone}} dest=/etc/timezone owner=root group=root mode=0644 backup=yes
  notify:
    - update timezone

- name: Allow sudo without password
  lineinfile: dest=/etc/sudoers state=present regexp='^%sudo\s+ALL\=' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
